name: Docker

on: 
  push: 
    branches:
      - main

jobs: 
  build: 
    runs-on: php-7.2
    steps: 
      - run: docker pull php:7.2-apache

  test: 
    runs-on: php-7.2
    steps: 
      - run: docker images