name: GOAT

on: 
  push: 
    branches:
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Fase de construccion"

  test: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Fase de pruebas"

  ga: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Fase de pruebas QA"

  prod: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Fase de produccion"

      - name: "Obteniendo última versión del código"
        uses: actions/checkout@v2

      - name: "Instalar Horus"
        run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta

      - name: "Iniciar Horus"
        run: horusec start -p="./" --return-error -e="false"


      - name: Build Docker
        run: |
          docker build -t prueba .
          docker image ls